# Generated by Django 3.0.5 on 2020-11-26 17:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Snippet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('code', models.TextField(default='# write some code')),
                ('state', models.CharField(blank=True, default='', max_length=100)),
                ('language', models.CharField(choices=[('assembly_x86', 'assembly_x86'), ('c_cpp', 'c_cpp'), ('csharp', 'csharp'), ('css', 'css'), ('golang', 'golang'), ('html', 'html'), ('java', 'java'), ('javascript', 'javascript'), ('json', 'json'), ('jsx', 'jsx'), ('markdown', 'markdown'), ('mysql', 'mysql'), ('python', 'python'), ('ruby', 'ruby'), ('typescript', 'typescript'), ('xml', 'xml')], default='python', max_length=100)),
                ('private', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snippets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
