# Generated by Django 3.0.5 on 2020-11-22 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='private',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='language',
            field=models.CharField(choices=[('assembly_x86', 'assembly_x86'), ('c_cpp', 'c_cpp'), ('csharp', 'csharp'), ('css', 'css'), ('golang', 'golang'), ('html', 'html'), ('java', 'java'), ('javascript', 'javascript'), ('json', 'json'), ('jsx', 'jsx'), ('markdown', 'markdown'), ('mysql', 'mysql'), ('python', 'python'), ('ruby', 'ruby'), ('typescript', 'typescript'), ('xml', 'xml')], default='python', max_length=100),
        ),
    ]
