
export const FETCH_SNIPPETS = 'FETCH_SNIPPETS';
export const FETCH_SNIPPETS_SUCCESS = 'FETCH_SNIPPETS_SUCCESS';
export const FETCH_SNIPPETS_FAILURE = 'FETCH_SNIPPETS_FAILURE';

export const FETCH_PUBLIC_SNIPPETS = 'FETCH_PUBLIC_SNIPPETS';
export const FETCH_PUBLIC_SNIPPETS_SUCCESS = 'FETCH_PUBLIC_SNIPPETS_SUCCESS';
export const FETCH_PUBLIC_SNIPPETS_FAILURE = 'FETCH_PUBLIC_SNIPPETS_FAILURE';

export const DELETE_SNIPPET = 'DELETE_SNIPPET';

export const CREATE_SNIPPET = 'CREATE_SNIPPET';
export const UPDATE_SNIPPET = 'UPDATE_SNIPPET';

export const SAVE_SNIPPET = 'SAVE_SNIPPET';
export const SAVE_SNIPPET_REMOTE = 'SAVE_SNIPPET_REMOTE';

export const SET_CURRENT_SNIPPET_META = 'SET_CURRENT_SNIPPET_META';

export const CLOSE_SNIPPET = 'CLOSE_SNIPPET';

export const ACTIONS = {
	FETCH_SNIPPETS,
	FETCH_SNIPPETS_SUCCESS,
	FETCH_SNIPPETS_FAILURE,
	DELETE_SNIPPET,
};