
export const FETCH_SNIPPET = 'FETCH_SNIPPET';
export const FETCH_SNIPPET_SUCCESS = 'FETCH_SNIPPET_SUCCESS';
export const FETCH_SNIPPET_FAILURE = 'FETCH_SNIPPET_FAILURE';

export const FETCH_PAGINATED_SNIPPETS = 'FETCH_PAGINATED_SNIPPETS';
export const FETCH_PAGINATED_SNIPPETS_SUCCESS = 'FETCH_PAGINATED_SNIPPETS_SUCCESS';
export const FETCH_PAGINATED_SNIPPETS_FAILURE = 'FETCH_PAGINATED_SNIPPETS_FAILURE';

export const DELETE_SNIPPET = 'DELETE_SNIPPET';
export const DELETE_SNIPPET_SUCCESS = 'DELETE_SNIPPET_SUCCESS';
export const DELETE_SNIPPET_FAILURE = 'DELETE_SNIPPET_FAILURE';

export const CREATE_SNIPPET = 'CREATE_SNIPPET';
export const UPDATE_SNIPPET = 'UPDATE_SNIPPET';

export const SAVE_SNIPPET = 'SAVE_SNIPPET';
export const SAVE_SNIPPET_SUCCESS = 'SAVE_SNIPPET_SUCCESS';

export const ACTIONS = {
	FETCH_SNIPPET,
	FETCH_SNIPPET_SUCCESS,
	FETCH_SNIPPET_FAILURE,
	FETCH_PAGINATED_SNIPPETS,
	FETCH_PAGINATED_SNIPPETS_SUCCESS,
	FETCH_PAGINATED_SNIPPETS_FAILURE,
	DELETE_SNIPPET,
	DELETE_SNIPPET_SUCCESS,
	DELETE_SNIPPET_FAILURE,
};